In [2]:
import xgboost as xgb
import pandas as pd
import numpy as np
import seaborn as sns

/Users/jerry/anaconda3/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/Users/jerry/anaconda3/lib/python3.7/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)

In [3]:
train = pd.read_csv('/Users/jerry/Desktop/udemy courses/Kaggle数据分析/Avito Duplicate Ads Detection/train.csv')

In [4]:
train1 = train.drop(['locationID_x.1','locationID_y.1','categoryID_x.1','categoryID_y.1'],axis = 1)

In [5]:
train1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2991396 entries, 0 to 2991395
Data columns (total 31 columns):
Unnamed: 0            int64
itemID_1              int64
itemID_2              int64
isDuplicate           int64
generationMethod      int64
itemID_x              int64
categoryID_x          int64
title_x               object
description_x         object
images_array_x        object
attrsJSON_x           object
price_x               float64
locationID_x          int64
metroID_x             float64
lat_x                 float64
lon_x                 float64
itemID_y              int64
categoryID_y          int64
title_y               object
description_y         object
images_array_y        object
attrsJSON_y           object
price_y               float64
locationID_y          int64
metroID_y             float64
lat_y                 float64
lon_y                 float64
regionID_x            int64
regionID_y            int64
parentCategoryID_x    int64
parentCategoryID_y    int64
dtypes: float64(8), int64(15), object(8)
memory usage: 707.5+ MB

Classification Models: LDA, QDA, Logistic regression, SVM, Decision Trees, Random Forests, various forms of Boosting

# 1 Tree based methods

## 1.1 Decision Tree

In [6]:
#metroID有太多 missing data
#title, attrsJSON, description 不是英文
#images 暂时不用
#item id 重复了 

#'title_x','title_y', 'description_x', 'description_y'  尝试用一下
train2 = train1.drop(['Unnamed: 0',  'images_array_x',
                      'images_array_y', 'attrsJSON_x', 'attrsJSON_y', 'generationMethod', 'metroID_x', 
                      'metroID_y','itemID_x', 'itemID_y'], axis=1)

In [7]:
train2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2991396 entries, 0 to 2991395
Data columns (total 21 columns):
itemID_1              int64
itemID_2              int64
isDuplicate           int64
categoryID_x          int64
title_x               object
description_x         object
price_x               float64
locationID_x          int64
lat_x                 float64
lon_x                 float64
categoryID_y          int64
title_y               object
description_y         object
price_y               float64
locationID_y          int64
lat_y                 float64
lon_y                 float64
regionID_x            int64
regionID_y            int64
parentCategoryID_x    int64
parentCategoryID_y    int64
dtypes: float64(6), int64(11), object(4)
memory usage: 479.3+ MB

In [8]:
train3 = train2.dropna()
train3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2651916 entries, 0 to 2991395
Data columns (total 21 columns):
itemID_1              int64
itemID_2              int64
isDuplicate           int64
categoryID_x          int64
title_x               object
description_x         object
price_x               float64
locationID_x          int64
lat_x                 float64
lon_x                 float64
categoryID_y          int64
title_y               object
description_y         object
price_y               float64
locationID_y          int64
lat_y                 float64
lon_y                 float64
regionID_x            int64
regionID_y            int64
parentCategoryID_x    int64
parentCategoryID_y    int64
dtypes: float64(6), int64(11), object(4)
memory usage: 445.1+ MB

In [16]:
train3.head(5)

,itemID_1,itemID_2,isDuplicate,categoryID_x,title_x,description_x,price_x,locationID_x,lat_x,lon_x,...,title_y,description_y,price_y,locationID_y,lat_y,lon_y,regionID_x,regionID_y,parentCategoryID_x,parentCategoryID_y
0,1,4112648,1,81,Продам Камаз 6520,Продам Камаз 6520 20 тонн,300000.0,648140,64.686946,30.815924,...,Продам Камаз 6520,Продам Камаз 6520 20 тонн,300000.0,648140,64.686946,30.815924,648070,648070,1,1
1,3,1991275,1,14,Yamaha r6,Весь в тюнинге.,300000.0,639040,55.678037,37.256548,...,Yamaha R6,Весь в тюнинге. Возможен торг,330000.0,639040,55.678037,37.256548,637680,637680,1,1
2,4,1223296,0,84,iPhone 3gs 8gb,"Телефон в хорошем состоянии, трещин и сколов н...",3500.0,640650,56.239398,43.460458,...,iPhone 3gs 32gb,"В отличном состоянии, в комплекте зарядник и к...",3500.0,640650,56.239398,43.460458,640310,640310,6,6
3,7,1058851,1,84,Xiaomi Mi4 3гб RAM + 16гб ROM белый,"Отличный подарок на новый год от ""китайской ap...",13500.0,662210,55.777170,37.586194,...,Смартфон Xiaomi Mi4 3гб RAM + 16гб ROM белый,"Отличный подарок на новый год от ""китайской ap...",13500.0,662210,56.135459,47.235484,662000,662000,6,6
4,8,2161930,1,39,Лыжные ботинки,"Лыжные ботинки в хорошем состоянии, 34 размер",500.0,624360,55.777170,37.586194,...,Ботинки для лыж,"Ботинки 34 размер, в хорошем состоянии",600.0,624360,55.777170,37.586194,624300,624300,7,7

In [63]:
train3.isna().sum()

itemID_1              0
itemID_2              0
isDuplicate           0
categoryID_x          0
title_x               0
description_x         0
price_x               0
locationID_x          0
lat_x                 0
lon_x                 0
categoryID_y          0
title_y               0
description_y         0
price_y               0
locationID_y          0
lat_y                 0
lon_y                 0
regionID_x            0
regionID_y            0
parentCategoryID_x    0
parentCategoryID_y    0
dtype: int64

In [35]:
#如何两个商品是一样的，那么price,location,lat,lon,category,region,parentcategory
#所以相减 看一下结果是不是0
import math 

y = train3.isDuplicate

price = abs(train3.price_x - train3.price_y)/train3[["price_x", "price_y"]].min(axis=1)
location = 1*(train3.locationID_x == train3.locationID_y)

lat = abs(train3.lat_x - train3.lat_y)
lon = abs(train3.lon_x - train3.lon_y)
distance = (lat**2 + lon**2)**(.5)

description = 1*(train3.description_x == train3.description_y)
title = 1*(train3.title_x == train3.title_y)
category = 1*(train3.categoryID_x == train3.categoryID_y)
region = 1*(train3.regionID_x == train3.regionID_y)
parentCategory = 1*(train3.parentCategoryID_x == train3.parentCategoryID_y)


d = {'price': price, 'location': location, 
     'distance':distance,
     'description':description, 'title':title, 
     'category': category, 'region': region, 'parentCategory': parentCategory}
X = pd.DataFrame(data=d)

In [36]:
X.head()

,price,location,distance,description,title,category,region,parentCategory
0,0.0,1,0.00000,1,1,1,1,1
1,0.1,1,0.00000,0,0,1,1,1
2,0.0,1,0.00000,0,0,1,1,1
3,0.0,1,9.65594,0,0,1,1,1
4,0.2,1,0.00000,0,0,1,1,1

In [37]:
y = train3[['isDuplicate']]

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
model = dtree.fit(X_train,y_train)

In [39]:
prediction = model.predict(X_test)

In [40]:
prediction

array([0, 0, 1, ..., 0, 1, 0])

In [41]:
from sklearn.metrics import classification_report, confusion_matrix

In [42]:
print(confusion_matrix(y_test, prediction))

[[371317 143642]
 [106495 253679]]

In [43]:
print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       0.78      0.72      0.75    514959
           1       0.64      0.70      0.67    360174

   micro avg       0.71      0.71      0.71    875133
   macro avg       0.71      0.71      0.71    875133
weighted avg       0.72      0.71      0.72    875133

We have a pretty good prediction already for the decision tree with high precision.

## 1.2 Random Forest

In [145]:
from sklearn.ensemble import RandomForestClassifier

In [146]:
rfc = RandomForestClassifier(n_estimators = 50)

In [147]:
rfc.fit(X_train, y_train)

/Users/jerry/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [148]:
rfc_pred = rfc.predict(X_test)

In [149]:
print(confusion_matrix(y_test, rfc_pred))

[[369953 145006]
 [102649 257525]]

In [150]:
print(classification_report(y_test, rfc_pred))

              precision    recall  f1-score   support

           0       0.78      0.72      0.75    514959
           1       0.64      0.72      0.68    360174

   micro avg       0.72      0.72      0.72    875133
   macro avg       0.71      0.72      0.71    875133
weighted avg       0.72      0.72      0.72    875133

There is no huge improvement over the simple decision tree but random forest is still a bit better.

In [151]:
rfc_pred_prob = rfc.predict_proba(X_test)[:,1]

In [152]:
import numpy as np
from sklearn import metrics

In [153]:
y_test1 = np.array(y_test['isDuplicate'])
y_test1

array([0, 0, 1, ..., 0, 1, 0])

In [154]:
rfc_pred_prob1 = np.array(rfc_pred_prob)
rfc_pred_prob1

array([0.05      , 0.0793466 , 0.52764447, ..., 0.2443473 , 0.52764447,
       0.18756787])

In [155]:
fpr, tpr, thresholds = metrics.roc_curve(y_test1, rfc_pred_prob1)
metrics.auc(fpr, tpr)

0.7866579324044078

# Test Data

In [97]:
test = pd.read_csv('/Users/jerry/Desktop/udemy courses/Kaggle数据分析/Avito Duplicate Ads Detection/test.csv')

In [98]:
test1 = test.drop(['locationID_x.1','locationID_y.1','categoryID_x.1','categoryID_y.1'],axis = 1)

In [99]:
test2 = test1.drop(['Unnamed: 0','images_array_x',
                      'images_array_y', 'attrsJSON_x', 'attrsJSON_y', 'metroID_x', 
                      'metroID_y','itemID_x', 'itemID_y'], axis=1)

In [100]:
test2.head()

,id,itemID_1,itemID_2,categoryID_x,title_x,description_x,price_x,locationID_x,lat_x,lon_x,...,title_y,description_y,price_y,locationID_y,lat_y,lon_y,regionID_x,regionID_y,parentCategoryID_x,parentCategoryID_y
0,0,5,4670875,115,Сотрудничество салонам кухонной мебели,Сотрудничество салонам кухонной мебели.\nТребу...,NaN,637640,55.760211,37.577211,...,Сотрудничество агенствам недвижимости в Москве,Сотрудничество агенствам недвижимости в МОСКВЕ.,NaN,637640,55.760211,37.577211,637640,637640,113,113
1,1,5,787210,115,Сотрудничество салонам кухонной мебели,Сотрудничество салонам кухонной мебели.\nТребу...,NaN,637640,55.760211,37.577211,...,Сотрудничество агенствам недвижимости в москве,Сотрудничество агенствам недвижимости в МОСКВЕ.,NaN,637640,55.760211,37.577211,637640,637640,113,113
2,2,6,1705280,10,Радар-детектор,Продам радар-детектор в идеальном состоянии!Пр...,NaN,637160,59.645846,33.513035,...,Радар-детектор,Продам радар-детектор в идеальном состоянии! П...,1500.0,637160,59.645846,33.513035,636370,636370,1,1
3,3,11,3020777,101,Зарядка для ноутбука Lenovo,"Зарядное устройство для ноутбука Lenovo, (19v,...",1300.0,650400,55.817608,49.097646,...,Б у батарейки для ноутбука,б у батарейки. отправка по рФ. Звоните с 10-00...,490.0,650400,55.817608,49.097646,650130,650130,6,6
4,4,23,5316130,27,"Кожаная opигинaльнaя куpткa- ""косyxa"" -Roundtree",Бренд: Roundtree & Yorke®\nMoдель: Heritage ...,15000.0,637640,55.827080,37.437604,...,"Кожаная кypткa- ""кocyxa"" -Roundtrее-And-Yоrkе",Бренд: Roundtree & Yorke®\nMoдель: Heritage ...,15000.0,637640,55.827080,37.437604,637640,637640,5,5

In [101]:
test2.isna().sum()

id                         0
itemID_1                   0
itemID_2                   0
categoryID_x               0
title_x                    2
description_x             25
price_x               129371
locationID_x               0
lat_x                      0
lon_x                      0
categoryID_y               0
title_y                    0
description_y             24
price_y               129700
locationID_y               0
lat_y                      0
lon_y                      0
regionID_x                 0
regionID_y                 0
parentCategoryID_x         0
parentCategoryID_y         0
dtype: int64

In [102]:
test2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044196 entries, 0 to 1044195
Data columns (total 21 columns):
id                    1044196 non-null int64
itemID_1              1044196 non-null int64
itemID_2              1044196 non-null int64
categoryID_x          1044196 non-null int64
title_x               1044194 non-null object
description_x         1044171 non-null object
price_x               914825 non-null float64
locationID_x          1044196 non-null int64
lat_x                 1044196 non-null float64
lon_x                 1044196 non-null float64
categoryID_y          1044196 non-null int64
title_y               1044196 non-null object
description_y         1044172 non-null object
price_y               914496 non-null float64
locationID_y          1044196 non-null int64
lat_y                 1044196 non-null float64
lon_y                 1044196 non-null float64
regionID_x            1044196 non-null int64
regionID_y            1044196 non-null int64
parentCategoryID_x    1044196 non-null int64
parentCategoryID_y    1044196 non-null int64
dtypes: float64(6), int64(11), object(4)
memory usage: 167.3+ MB

In [66]:
test2[test2.price_x.isnull()]

,id,itemID_1,itemID_2,categoryID_x,title_x,description_x,price_x,locationID_x,lat_x,lon_x,...,title_y,description_y,price_y,locationID_y,lat_y,lon_y,regionID_x,regionID_y,parentCategoryID_x,parentCategoryID_y
0,0,5,4670875,115,Сотрудничество салонам кухонной мебели,Сотрудничество салонам кухонной мебели.\nТребу...,NaN,637640,55.760211,37.577211,...,Сотрудничество агенствам недвижимости в Москве,Сотрудничество агенствам недвижимости в МОСКВЕ.,NaN,637640,55.760211,37.577211,637640,637640,113,113
1,1,5,787210,115,Сотрудничество салонам кухонной мебели,Сотрудничество салонам кухонной мебели.\nТребу...,NaN,637640,55.760211,37.577211,...,Сотрудничество агенствам недвижимости в москве,Сотрудничество агенствам недвижимости в МОСКВЕ.,NaN,637640,55.760211,37.577211,637640,637640,113,113
2,2,6,1705280,10,Радар-детектор,Продам радар-детектор в идеальном состоянии!Пр...,NaN,637160,59.645846,33.513035,...,Радар-детектор,Продам радар-детектор в идеальном состоянии! П...,1500.0,637160,59.645846,33.513035,636370,636370,1,1
6,6,30,2922567,10,Комплект R14,Кама евро 129 на штамповках. в нормальном сост...,NaN,650400,55.750109,49.207735,...,Комплект R14,Кама 129 \n14 радиус 2 шт 175 на 70 и 2 шт 175...,4000.0,650440,56.184806,50.902191,650130,650130,1,1
8,8,36,2724090,97,Игры для Playstation 3,1)Battlefield hardline-1000р.(PS3).\n2)Стартре...,NaN,653240,59.842110,30.250588,...,Игры для Playstation 3,Naruto Storm 1.\nNaruto Storm 2.\nNaruto Storm...,4500.0,653240,59.842110,30.250588,653240,653240,6,6
21,21,96,2677733,115,Плиточник ищет работу,Качественно и не дорого выложу плитку любой сл...,NaN,650400,55.855851,49.084495,...,Штукатур маляр ищет работу,Качественно и не дорого выполню штукатурные и ...,NaN,650400,55.855851,49.084495,650130,650130,113,113
22,22,96,5726138,115,Плиточник ищет работу,Качественно и не дорого выложу плитку любой сл...,NaN,650400,55.855851,49.084495,...,"Строительство домов, дач, бань",Качественно и не дорого построим дом дачу баню...,NaN,650400,55.855851,49.084495,650130,650130,113,113
23,23,96,2645015,115,Плиточник ищет работу,Качественно и не дорого выложу плитку любой сл...,NaN,650400,55.855851,49.084495,...,Баня под ключ,Строительство бань под ключ . не дорого. По ва...,NaN,650400,55.855851,49.084495,650130,650130,113,113
24,24,96,5219049,115,Плиточник ищет работу,Качественно и не дорого выложу плитку любой сл...,NaN,650400,55.855851,49.084495,...,Строитель ищет работу,Если вы строите дом дачу баню или ремонт кварт...,NaN,650400,55.855851,49.084495,650130,650130,113,113
25,25,96,779617,115,Плиточник ищет работу,Качественно и не дорого выложу плитку любой сл...,NaN,650400,55.855851,49.084495,...,Плиточник,Качественно и не дорого выложу плитку любой сл...,NaN,650400,55.855851,49.084495,650130,650130,113,113
26,26,96,3228677,115,Плиточник ищет работу,Качественно и не дорого выложу плитку любой сл...,NaN,650400,55.855851,49.084495,...,Плиточник ищет работу,"Качественно и не дорого выложу плитку , природ...",NaN,650400,55.855851,49.084495,650130,650130,113,113
30,30,119,2567852,112,Строительство,Ищу работу,NaN,635860,55.453085,65.346508,...,Строительство,Бригада из 3-4 чел. ищет работу по строительст...,NaN,635860,55.453085,65.346508,635730,635730,110,110
45,45,175,3455555,112,Оператор станков с чпу,"Исполнительный, пунктуальный, готовый много уч...",NaN,648760,56.637263,47.886673,...,Плотник/ Столяр,"Исполнительный, пунктуальный, готовый много уч...",NaN,648760,56.637263,47.886673,648730,648730,110,110
52,52,207,5266455,114,Требуется кладовщик,"Знание запчастей к автомобилям МАЗ, КАМАЗ, ГАЗ...",NaN,632760,44.920647,41.079626,...,Требуется продавец в магазин запчастей,"Обязательно знание автомобилей МАЗ, КАМАЗ, про...",NaN,632760,44.920647,41.079626,632660,632660,113,113
55,55,223,1780040,89,Отдам в хорошие руки,"Отдам щенка( кабель) 7 месяцев,окрас шоколадны...",NaN,661420,55.152161,61.387103,...,Отдам в хорошие руки,"Отдам щенка( кабель),помесь северной лайки и о...",NaN,661420,55.152161,61.387103,660710,660710,35,35
61,61,231,5596236,34,Ремонт Велосипедов,"Ремонт Велосипедов,регулировка,настройка,диагн...",NaN,632490,57.767256,40.926984,...,Ремонт велосипедов,Сделаю полную настройку и регулировку велосипе...,100.0,632490,57.767256,40.926984,632390,632390,7,7
62,62,232,2773891,40,Стальные емкости для азс 25 м3,"ООО ""Производство Резервуарного Оборудования"" ...",NaN,638110,55.623937,37.843908,...,Cтальные силосы для цемента 100 тонн,"ООО ""Производство Резервуарного Оборудования"" ...",NaN,639040,55.678037,37.256548,637680,637680,8,8
64,64,234,4773703,112,Разнорабочий,Разнорабочий\nПодсобник\nГрузчик\nРассмотрю вс...,NaN,655100,54.779800,31.999095,...,Подсобник/Разнорабочий,"Выгрузка, погрузка\nПодать, поднести, принести...",NaN,655100,54.779800,31.999095,654860,654860,110,110
70,70,254,5681889,10,Запчасти,продам на запчасти,NaN,656901,56.860477,35.904539,...,На запчасти,Продам на запчасти,NaN,656980,56.171272,34.577224,656890,656890,1,1
88,88,332,4989269,84,Highscreen boost 2se и Explay A600Любые варианты,Интиресуют любые варианты продажи и обмена.\nH...,NaN,633570,45.440068,40.557659,...,Highscreen Boost 2 se,Идеально рабочий телефон! \nОписание смотрите ...,NaN,633570,45.440068,40.557659,632660,632660,6,6
98,98,376,3107914,83,Продам книги Буровзрывные работы,Волох А.С. Основы управления действием взрыва...,NaN,641780,55.026537,82.921466,...,Продам книги по бвр,Волох А.С. Основы управления действием взрыва...,NaN,641780,55.026537,82.921466,641470,641470,7,7
116,116,423,1225838,98,Срочно продам,Продам срочно ноутбук новый брали за 72тыс пол...,NaN,647030,42.062362,48.298397,...,Ноутбук асус,Продам срочно ноутбук новый брали за 70 тыс по...,NaN,647150,42.878731,47.639672,646710,646710,6,6
120,120,446,1753942,114,Наращивание ногтей Шеллак,"Наращивание ногтей, гелем на формы! Любой диза...",NaN,649870,43.018678,44.680172,...,Качественное наращивание ногтей Шеллак,"Дорогие девушки, предлагаю КАЧЕСТВЕННЫЕ и НЕДО...",NaN,649870,43.018678,44.680172,649820,649820,113,113
126,126,479,1609611,89,Щенки,Отдам щенков в добрые руки (4 девочки ) подар...,NaN,649870,43.018678,44.680172,...,Щенки,ОТДАМ ЩЕНКОВ В ДОБРЫЕ РУКИ 🙏🏻 ПОДАРИТЕ МАЛЫШАМ...,NaN,649870,43.018678,44.680172,649820,649820,35,35
130,130,502,1861714,112,"Няня, помошница по хозяйсту, сиделка с прожива...","Женщина,55 лет,РФ.Живу в Нижнем Новгороде, Без...",NaN,637640,55.753653,37.619800,...,Сиделка -компаньонка с проживанием,"Женщина 55 лет,РФ.Живу в Нижнем Новгороде. Без...",NaN,637640,55.753653,37.619800,637640,637640,110,110
131,131,503,3187214,102,Заброска туристов,Заброска туристов на все реки и озёра Лоухског...,NaN,648160,66.072590,33.005208,...,Заброска туристов,Заброска туристов на реки и озёра Лоухского ра...,NaN,648160,66.072590,33.005208,648070,648070,7,7
140,140,517,1213754,114,Все типы отделочных и ремонтных работ,"Выполним все виды отделочных,ремонтных работ к...",NaN,652430,54.619886,39.744954,...,Постройка домов. бань. беседок и отделка,"Выполним строительство и отделку домов,бань,бе...",NaN,652430,54.619886,39.744954,652220,652220,113,113
141,141,517,3980749,114,Все типы отделочных и ремонтных работ,"Выполним все виды отделочных,ремонтных работ к...",NaN,652430,54.619886,39.744954,...,"Постройка бань, домов, беседок","Выполним строительство домов,бань беседок гара...",NaN,652430,54.619886,39.744954,652220,652220,113,113
142,142,520,1015071,10,Продам фары на Datsun ON-DO,Продаю фары и радиатор на автомобиль Datsun ON...,NaN,621630,53.356132,83.749620,...,Фары на Datsun ON-Do,Продам фары. Цена договорная.,NaN,621630,53.356132,83.749620,621590,621590,1,1
150,150,557,1030381,84,"Зарядка для Nokia(обмен, отправляю почтой)","зарядка Nokia Универсальная AC-3E,подходит для...",NaN,637640,55.753653,37.619800,...,Оригнальная зарядка Нокиа(возможен обмен),"зарядка Nokia Универсальная AC-3E,подходит для...",NaN,637640,55.753653,37.619800,637640,637640,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1043967,1043967,6021408,6054193,19,Профлист сс10-1165 оцинк,Предлагаем на заказ любой длины до 12м профнас...,NaN,642790,51.768060,55.097449,...,Профлисты любой длины,Изготавливаем качественный профнстил любой дли...,NaN,642860,53.321846,54.125697,642480,642480,2,2
1043974,1043974,6023043,6056264,10,Круз бампер,круз бампера переднии и заднии возможно в цвет,NaN,644200,58.004785,56.237654,...,Бампер,бампера на все машины .возможно в цвет . возм...,NaN,643800,57.866646,56.101272,643700,643700,1,1
1043983,1043983,6024202,6071679,10,"Продаю запчасти камаз, маз","продаю чулок передний,задний,балку переднюю,ре...",NaN,635860,55.453085,65.346508,...,"Меняю кабины камаз, маз","меняю кабины КАМАЗ, МАЗ и другие запчасти ,б/у...",NaN,635860,55.453085,65.346508,635730,635730,1,1
1043988,1043988,6025132,6054732,81,Мтз-80,Продаю трактор МТЗ 80 в отличном состоянии 199...,NaN,655320,45.105104,43.429358,...,Экскаваторная навеска,Продается экскаваторная навеска на МТЗ в отлич...,NaN,655320,45.105104,43.429358,655190,655190,1,1
1044010,1044010,6029532,6047289,90,Отдам кота в добрые руки,"Отдам кота в добрые руки.\nКоту 1 год,костриро...",NaN,640860,56.325130,43.913262,...,Отдам кота в добрые руки,"Отдам кота в добрые руки. Коту 1 год,костриров...",NaN,640860,56.325130,43.913262,640310,640310,35,35
1044027,1044027,6033805,6067896,114,Услуги электрика,"ремонт и замена проводки , розеток, светильник...",NaN,659250,58.137661,52.637350,...,Ремонт электропроводки,"Замена электропроводки , велючателей, разеток,...",NaN,659250,58.137661,52.637350,659200,659200,113,113
1044028,1044028,6033830,6047175,89,В добрые руки замечательную собаку,"Крупная девчушка, месяцев 7 от роду, с очень и...",NaN,654070,56.858056,60.600816,...,"Герда, умница и красавица","Крупная девушка, месяцев 7 от роду, с очень иг...",NaN,654070,56.858056,60.600816,653700,653700,35,35
1044031,1044031,6034762,6082366,112,Сделаем ремонт евро,Здравствуйте\nЕсть опытных мастеров\nСпециалис...,NaN,637640,55.803691,37.403118,...,Мастер по малярный работы,Здравствуйте Есть бригада специалисты по ремон...,NaN,637640,55.803691,37.403118,637640,637640,110,110
1044033,1044033,6035475,6108556,112,Инженер-геодезист,"в настоящее время (с 2003) ИП, наличие парка и...",NaN,653240,59.938806,30.314278,...,Инженер-геодезист,Стаж боле 30 лет. Все виды работ. Комплекс инс...,NaN,653240,59.938806,30.314278,653240,653240,110,110
1044045,1044045,6038905,6039738,112,Сварщик 3-го разряда,"Без вредных привычек.Ручная дуговая,полуавтомат.",NaN,641780,55.059291,82.912569,...,Сварщик,"Ответственный,без вредных привычек.Ручная дуго...",NaN,641780,55.059291,82.912569,641470,641470,110,110
1044046,1044046,6039168,6100502,115,Укладка керамической плитки,Требуется облицевать камин керамической плитко...,NaN,624470,55.902217,39.070373,...,Укладка керамической плитки,Требуется профессиональная облицовка керамиче...,NaN,624470,55.902217,39.070373,624300,624300,113,113
1044055,1044055,6042744,6042967,20,"Мебель, стулья, столы, комоды",Стулья \nСтолы\nКомоды\nПуфики \nБанкетки \nДи...,NaN,637640,55.753653,37.619800,...,Комоды,Мы производим мебель из массива,NaN,637640,55.753653,37.619800,637640,637640,2,2
1044056,1044056,6042956,6089437,114,Ремонт Компьютеров,Выполняю широкий спектр услуг по ремонту компь...,NaN,661950,52.033297,113.501238,...,Ремонт компьютеров,"Ремонт компьютеров, ноутбуков.\nВосстановление...",NaN,661950,52.033297,113.501238,661460,661460,113,113
1044059,1044059,6044300,6053389,112,Работник с опытом,Русский молодой с опытом и умение работы на ст...,NaN,653240,59.966394,30.311502,...,Рабочий с опытом,Русский умею обращаться с любым видом инструме...,NaN,653240,59.985377,30.300902,653240,653240,110,110
1044072,1044072,6046704,6103177,10,Запчасти авто газ ВАЗ,Волга\nДвигатель 406 27000руб\nПередние седени...,NaN,654410,57.925403,60.003383,...,Запчасти,Волга\nДвигатель 406 27000руб\nПередние седени...,NaN,654410,57.925403,60.003383,653700,653700,1,1
1044085,1044085,6050737,6066948,89,Хотошо,Щенки Хотошо (бурят-монгольский волкодав) чист...,NaN,653271,51.823816,107.599306,...,Хотошо,Щенки Хотошо (бурят-монгольский волкодав) чист...,NaN,653271,51.823816,107.599306,623845,623845,35,35
1044087,1044087,6050840,6100826,40,Станок токарный бу 16к20,Продажа токарных станков после проведенного ре...,NaN,658080,54.193802,37.619028,...,Станок токарный 16К25 рмц 1000,"Произведен капитальный ремонт, соответствует п...",NaN,658080,54.193802,37.619028,657610,657610,8,8
1044105,1044105,6054831,6054962,82,Деревенская картошка с доставкой до квартиры,●▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬●\n░░░░░►Картошка отборная ...,NaN,650510,55.766293,52.430109,...,Деревенская картошка с доставкой до квартиры,●▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬●\n░░░░░►Картошка отборная ...,NaN,650510,55.766293,52.430109,650130,650130,2,2
1044106,1044106,6054910,6084324,114,Шугаринг,"Студия Шугаринга . Уссурийская 8,каб 5",NaN,660250,48.460732,135.056475,...,Шугаринг,Отдельный кабинет наш адрес ул. Уссурийская 8 ...,NaN,660250,48.460732,135.056475,659930,659930,113,113
1044110,1044110,6055541,6066148,29,Комбенизон ёмаё,Продам комбенизон для малышки Российской фирмы...,NaN,653241,51.537652,46.004549,...,Комбенезон Ёмаё,Продам комбенизон для малышки Российской фирмы...,2000.0,653241,51.537652,46.004549,653420,653420,5,5
1044112,1044112,6056384,6083701,24,Куплю 1-к квартиру,Куплю 1-2-х комнатную квартиру в любом районе ...,NaN,637640,55.659460,37.750514,...,Сниму 1-к квартиру,Сниму 1-2-х комнатную квартиру в любом районе ...,NaN,637640,55.659460,37.750514,637640,637640,4,4
1044114,1044114,6057156,6083884,27,Туфли с бантом даром,Добрый день! Отдам даром лиловые тфули с банто...,NaN,654070,56.836298,60.599846,...,Ботильоны даром,"Добрый день! Передам даром ботильоны, на замоч...",NaN,654070,56.836298,60.599846,653700,653700,5,5
1044117,1044117,6058540,6067068,112,Рассмотрю все варианты,"Не женат, детей нет, владею ПК свободно, ВУ н...",NaN,659020,57.182636,65.558421,...,Рассмотрю все варианты,"Не женат, детей нет, владею ПК свободно, ВУ не...",NaN,659020,57.182636,65.558421,658170,658170,110,110
1044123,1044123,6059474,6073515,93,Пушок,Голубогазый красавчик от породистого папы. Оче...,NaN,655570,44.144453,43.015522,...,Ручные малыши,Продам малышей- декоративных крольчат от гладк...,NaN,655570,44.144453,43.015522,655190,655190,35,35
1044142,1044142,6064711,6084340,27,Платье,р-р 38-40. из трикотажа.,NaN,661420,55.152161,61.387103,...,Рубашка,"р-р 40-42, в полоску",300.0,661420,55.152161,61.387103,660710,660710,5,5
1044148,1044148,6066948,6110221,89,Хотошо,Щенки Хотошо (бурят-монгольский волкодав) чист...,NaN,653271,51.823816,107.599306,...,Хотошо,Щенки Хотошо (бурят-монгольский волкодав) чист...,NaN,653271,51.823816,107.599306,623845,623845,35,35
1044161,1044161,6071717,6109797,90,Котик вислоухий(фолд) окрас черное пятно на се...,Вислоухий котик(скоттиш фолд) окрас черное пят...,NaN,646600,54.738437,55.983161,...,Вислоухий кот окрас черное пятно на серебре,"Вислоухий котик окрас черное пятно на серебре,...",NaN,646600,54.738437,55.983161,645790,645790,35,35
1044163,1044163,6072706,6103418,29,Продаются кофточки,продаются кофточки в идеальном состояние. за в...,NaN,646400,54.486320,53.492631,...,Продаются спортивки на девочку,продаются спортивки красивые на девочку все и...,350.0,646400,54.486320,53.492631,645790,645790,5,5
1044173,1044173,6078352,6083888,112,"Подсобный, разнорабочий","Шпаклевка,штукатурка,монтаж,гипсокартон и т.д.",NaN,656830,52.722032,41.454241,...,Грузчик-разнорабочий,"Штукатурка,шпаклевка,покраска и т.д",NaN,656830,52.722032,41.454241,656520,656520,110,110
1044179,1044179,6083495,6101372,30,Peg Perego gt3,Продаётся peg Perego gt3 прогулка дефект один ...,NaN,662810,57.622434,39.887894,...,Peg perego gt3,Продам прогулку!есть капор от солнца!дефект ви...,8000.0,662810,57.622434,39.887894,662530,662530,5,5

In [126]:
price1 = abs(test2.price_x - test2.price_y)/test2[["price_x", "price_y"]].min(axis=1)
location1 = 1*(test2.locationID_x == test2.locationID_y)

price1.fillna(price1.mean(), inplace=True) #data imputation using mean value

lat1 = abs(test2.lat_x - test2.lat_y)
lon1 = abs(test2.lon_x - test2.lon_y)
distance1 = (lat1**2 + lon1**2)**(.5)

description1 = 1*(test2.description_x == test2.description_y)
title1 = 1*(test2.title_x == test2.title_y)
category1 = 1*(test2.categoryID_x == test2.categoryID_y)
region1 = 1*(test2.regionID_x == test2.regionID_y)
parentCategory1 = 1*(test2.parentCategoryID_x == test2.parentCategoryID_y)


d1 = {'price': price1, 'location': location1, 
     'distance':distance1,
     'description':description1, 'title':title1, 
     'category': category1, 'region': region1, 'parentCategory': parentCategory1}
X1 = pd.DataFrame(data=d1)

In [131]:
X1.head()

,price,location,distance,description,title,category,region,parentCategory
0,61703.659451,1,0.0,0,0,1,1,1
1,61703.659451,1,0.0,0,0,1,1,1
2,61703.659451,1,0.0,0,1,1,1,1
3,1.653061,1,0.0,0,0,1,1,1
4,0.000000,1,0.0,1,0,1,1,1

In [132]:
X1.isna().sum() #price有很多nan，需要

price             0
location          0
distance          0
description       0
title             0
category          0
region            0
parentCategory    0
dtype: int64

In [133]:
list(X1.columns)

['price',
 'location',
 'distance',
 'description',
 'title',
 'category',
 'region',
 'parentCategory']

In [134]:
X1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044196 entries, 0 to 1044195
Data columns (total 8 columns):
price             1044196 non-null float64
location          1044196 non-null int64
distance          1044196 non-null float64
description       1044196 non-null int64
title             1044196 non-null int64
category          1044196 non-null int64
region            1044196 non-null int64
parentCategory    1044196 non-null int64
dtypes: float64(2), int64(6)
memory usage: 63.7 MB

We do not need imputation in the case.

In [74]:
## Imputation for whole dataframe

In [76]:
#from sklearn.impute import SimpleImputer
#import numpy as np
#imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
#imp_mean.fit(X1)
#X2 = imp_mean.transform(X1)

In [77]:
#X2.shape

In [78]:
#X3 = pd.DataFrame(data = X2, columns=list(X1.columns))

In [79]:
#X3.head()

## Prediction

In [135]:
pred_test = rfc.predict_proba(X1)[:,1]
pred_test = np.array(pred_test)

In [136]:
pred_test

array([0.04      , 0.04      , 0.78      , ..., 0.71062019, 0.17625459,
       0.40618754])

In [137]:
len(pred_test)

1044196

In [138]:
index = np.array(test2['id'].astype(np.int))

In [139]:
index

array([      0,       1,       2, ..., 1044193, 1044194, 1044195])

In [140]:
len(index)

1044196

In [141]:
pred_test1 = {'id':index,'probability':pred_test}

In [142]:
pred_test2 = pd.DataFrame(pred_test1, columns =['id','probability'])

In [143]:
pred_test2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044196 entries, 0 to 1044195
Data columns (total 2 columns):
id             1044196 non-null int64
probability    1044196 non-null float64
dtypes: float64(1), int64(1)
memory usage: 15.9 MB

In [144]:
pred_test2.to_csv('/Users/jerry/Desktop/udemy courses/Kaggle数据分析/Avito Duplicate Ads Detection/prediction.csv',index=False)